---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  attributes:
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    mysql:
      server_root_password: "randompass"
      server_repl_password: "randompass"
      server_debian_password: "randompass"
    holland:
      password: "randompass"

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]
  - name: centos-7.0
    run_list:
    - recipe[yum]

suites:
# tests those that consume via run lists
  - name: runlist
    run_list:
      - recipe[stack_commons::rabbitmq]
      - recipe[stack_commons::varnish]
      - recipe[wrapper::demo]
    attributes:
      stack_commons:
        demo:
          enabled: true
  - name: runlist_mongodb_standalone
    run_list:
      - recipe[stack_commons::mongodb_standalone]
      - recipe[wrapper::demo]
    attributes:
      stack_commons:
        demo:
          enabled: true
  - name: runlist_memcached
    run_list:
      - recipe[stack_commons::memcached]
      - recipe[wrapper::demo]
    attributes:
      stack_commons:
        demo:
          enabled: true
# tests those that consume via a wrapper recipe named 'default' because I have to
  - name: default
    run_list:
      - recipe[wrapper::default]
  - name: wrapper_mongodb_standalone
    run_list:
      - recipe[wrapper::mongodb_standalone]
  - name: wrapper_memcached
    run_list:
      - recipe[wrapper::memcached]
